# NumPy

- **Numerical python**
- Geometrical, calculus, arithmatic
- Collection of similar classes
- Classes are collection of similar variables and methods
- Performing numerical operations in python


- **Saving Code time**
- **No for loops**
- **Faster Execution**
- **Uses less memory over list**

In [ ]:
# Adding 2 lists
a = [1, 2, 3, 4] # a is a list
b = [10, 11, 12, 13] # b is a list

# both lists have same length
# now we want to add these two lists, element by element
print(a + b)


[1, 2, 3, 4, 10, 11, 12, 13]


#### Elementwise operations

In [ ]:
## rather than adding them together it concatenated it
## so to add them together we have to write a for loop
for item1, item2 in zip(a, b):
    c = item1 + item2
    print (c)


11
13
15
17


### Data structures
- Scalar
- Vector
- Arrays 
- Matrix (built in)

#### Arrays:
A Python Array is a collection of common type of data structures having elements with same data type. It is used to store collections of data. In Python programming, an arrays are handled by the “array” module. If you create arrays using the array module, elements of the array must be of the same numeric type.

NumPy is used for working with an array.

In [ ]:
!conda list # packages are in inactive mode as they will take so much space

## Importing libraries

- We can not just import libraries and call them directly as some libraries names are big
- Hence, we use alias such as np for numpy (conventional way)

In [ ]:
import numpy as np

### Scalar

In [ ]:
a = np.array(5)

In [ ]:
a.ndim # number of dimensions

0

### Vector

In [ ]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
a.ndim

1

In [ ]:
a = np.array([[1, 2, 3]])
print(a.T) # T is used to transpose the vector

[[1]
 [2]
 [3]]


### Matrix

In [ ]:
# now we are creating two dimensional array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a.ndim

2

In [ ]:
# now we are creating two dimensional array
a = np.matrix([(1, 2, 3), (4, 5, 6)])
print(a)


[[1 2 3]
 [4 5 6]]


In [ ]:
type(a)

numpy.ndarray

### shape

In [ ]:
a = np.matrix([(1, 2, 3), (4, 5, 6)])
print(a)
a.shape # shape function is used to examine the number of rows and columns

[[1 2 3]
 [4 5 6]]


(2, 3)

### Array of zeros

In [ ]:
np.zeros(4) # array having value 4 zeros 

array([0., 0., 0., 0.])

In [ ]:
np.zeros((3,4)) # array having value zero with three rows and four columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Array of ones

In [ ]:
np.ones(7,dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [ ]:
# Create a multidimensional array of 1
def add(a,b):
  return(a+b)

print(add(2,3))

getinput()
processdata()
result()


add()
  add()


5


In [ ]:
def factorial(n):
  if(n==0 or n==1):
    return 1
  elif n >0:
    return n*factorial(n-1)
  
print(factorial(5))

120


### Array of constant

In [ ]:
np.full((4, 3), 0) # here 4 is no of rows, 3 is no of columns and 10 is a constant value.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### arange

In [ ]:
a = np.arange(24, dtype = float) # similar to range function
print(a.dtype)
print(a)

float64
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [ ]:
np.arange(10, 75) # similar to range function

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74])

In [ ]:
np.arange(10, 75, 5) # similar to range function

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

### arrange z nos btwn x & y

In [ ]:
np.linspace(5,10, 4) # here create 4 different data points between 5 and 10 with equal gap


array([ 5.        ,  6.66666667,  8.33333333, 10.        ])

In [ ]:
np.linspace(2,10, 3)

array([ 2.,  6., 10.])

### Random numbers in ndarrays

In [ ]:
np.random.random((2,2)) # two rows and two columns

array([[0.76353293, 0.06198474],
       [0.70168861, 0.14656462]])

In [ ]:
np.random.random((1,7)) # one row and seven columns

array([[0.23065904, 0.93888806, 0.28439255, 0.68676051, 0.52073787,
        0.41940376, 0.20995131]])

In [ ]:
np.random.random((3,3)) # three rows and three columns

array([[0.16579701, 0.48317324, 0.08847372],
       [0.34068098, 0.75970421, 0.09233574],
       [0.00829749, 0.93214908, 0.46363265]])

### Identity matrix

- An Identity matrix is a square matrix that has 1s along its main diagonal and 0s everywhere else.

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### The Reshaping of NumPy Arrays

syntax: np.reshape(array,shape)

In [ ]:
a = np.array([[2,3,4],[4,5,6]])
print(a)
a.shape=(3,2)
print(a)

[[2 3 4]
 [4 5 6]]
[[2 3]
 [4 4]
 [5 6]]


### Size of NumPy array

In [ ]:
a = np.array([[2,3,4],[4,5,6]])
print(a)
print(a.size) # how many values there are in the array using the size attribute


[[2 3 4]
 [4 5 6]]
6


### flip

In [ ]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)


Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(np.flip(a,axis=1))


[[ 5  4  3  2  1]
 [10  9  8  7  6]]


In [ ]:
print(np.flip(a,axis=0))


[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [ ]:
print('Reversed array horizontally :','\n',np.flip(a,axis=0))

In [ ]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)


In [ ]:
print(a[::-1,::-1])

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


### sort

In [ ]:
a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[5,6,7,4],
              [9,2,3,7]])# sort along the column

print(a)

[[5 6 7 4]
 [9 2 3 7]]


In [ ]:
print(np.sort(a, kind='quicksort',axis=1))

[[1 6]
 [3 4]]


In [ ]:
# sort along the row
print(np.sort(a, kind='mergresort',axis=0))

[[5 2 3 4]
 [9 6 7 7]]


## Basic mathematics using numPy

In [ ]:
# Adding 2 lists
a = [1, 2, 3, 4] # a is a list
b = [10, 11, 12, 13] # b is a list

# both lists have same length
# now we want to add these two lists, element by element
print(a + b)


[1, 2, 3, 4, 10, 11, 12, 13]


In [ ]:
a + 10

TypeError: ignored

## Addition using numpy

In [ ]:
a = np.array([1, 2, 3, 4]) # a is an array
# a + 10 # we can simply do all basic mathematics
# a - 10
# a * 10
# a / 10
a // 10

array([0, 0, 0, 0])

In [ ]:
##type 1
a = np.array([10, 20])
print(a)
np.sum([10,20])

[10 20]


30

In [ ]:
#type 2
a,b = 10,20
np.sum([a,b])

30

In [ ]:
#type 3
a = np.array([[1, 2], [3, 1]])
print(a)
np.sum(a, axis=0) # axis o means column wise

[[1 2]
 [3 1]]


array([4, 3])

In [ ]:
#type 4
a = np.array([[1, 2], [3, 1]])
print(a)
np.sum(a, axis=1) # axis 1 means row wise

[[1 2]
 [3 1]]


7

In [ ]:
a + 10 # adding a constant value in a matrix

array([[11, 12],
       [13, 11]])

### subtraction using numpy

In [ ]:
np.subtract(10,20)

-10

### other maths functions using numpy

In [ ]:
np.multiply(2,3) #multiply

6

In [ ]:
np.divide(10,5)  #divide

2.0

In [ ]:
#multiply arrays
a = np.array([2,3,4]) 
b = np.array([5,6,3])
np.multiply(a,b) # element wise multiplication

array([10, 18, 12])

In [ ]:
#exp, sqrt
a=[1,2,4]
print(np.exp(a))
print(np.sqrt(a))

[ 2.71828183  7.3890561  54.59815003]
[1.         1.41421356 2.        ]


### Basic statistics

In [ ]:
age = [23, 34, 27, 30, 32, 31, 33, 26, 28, 25]
np.std(age) # standard deviation

3.477067730142742

In [ ]:
np.std(age, ddof = 1) # ddof means the Delta Degrees of Freedom. It actually means n - 1

3.665151201974256

In [ ]:
np.var(age, ddof = 1) # ddof means the Delta Degrees of Freedom. It actually means n - 1

In [ ]:
np.mean(age)

28.9

In [ ]:
np.median(age)

29.0

In [ ]:
np.min(age)
np.mode(age)

AttributeError: ignored

In [ ]:
np.max(age)

34

In [ ]:
a = np.array([[1,6],
[4,3]])
print(a)
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

[[1 6]
 [4 3]]
Min : [1 3]
Max : [6 4]


## Boolean indexing

In [ ]:
# What will be the output of following function?
Age = np.array([75, 65, 25, 92, 18, 14, 22])
Age <= 18

array([False, False, False, False,  True,  True, False])

In [ ]:
Age_18 = Age[Age <=18]
Age_18

array([18, 14])

## array comparison

In [ ]:
# What will be the output of following code?
a = [3,2,3]
b = [3,2,4]
c = [1,2,3]
np.equal(a,b)

array([ True,  True, False])

In [ ]:
#array wise comparison
a = [1,2,3]
b = [1,2,3]
c = [1,2,4]
np.array_equal(a,c)

False

## broadcasting
 - the ability of NumPy to treat arrays of different shapes during arithmetic operations

In [ ]:
a = np.array([[1,1,1],[10,10,10],[20,20,20],[30,30,30]])
b = np.array([1, 2, 3])
print(a.shape)
print(b.shape)
print('First array: \n',a,'\n')
print('Second array: \n',b,'\n')

print(a+b)

(4, 3)
(3,)
First array: 
 [[ 1  1  1]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

Second array: 
 [1 2 3] 

[[ 2  3  4]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


## Stacking

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 11, 12, 13])


In [ ]:
print(np.vstack((a, b))) # vertical stacking

[[ 1  2  3  4]
 [10 11 12 13]]


In [ ]:
print(np.hstack((a, b))) # horizontal stacking

[ 1  2  3  4 10 11 12 13]


## concatenate 2 arrays

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [ ]:
#combining col-wise
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

## Splitting Array

In [ ]:
# Syntax: numpy.reshape(array, shape)
x = np.arange(16).reshape(4,4) # first array and then shape
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#split the same array horiz - after 2 cols
x = np.arange(16).reshape(4,4)
print(x, "\n\n")
np.hsplit(x,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 




[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## Indexing & Slicing

In [ ]:
a = ['n','o','p','e','t','o','h','i','m']
a[0:5]

['n', 'o', 'p', 'e', 't']

In [ ]:
# to slice arrays based on arrays
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[0]

array([1, 2, 3])

In [ ]:
# to extract 1st array
a[:,2:3]

array([[3],
       [6],
       [9]])

In [ ]:
# to extract, 2nd and 3rd element from 1st array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[:1,1:]

array([[2, 3]])

In [ ]:
#to extract only 2,3,5 and 6 from the arrays, i.e.,1st 2 rows (horiz) and after 1st col(vertically)
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
#to extract 5,6,8 and 9 from the array
a[1:,1:]

## reading files

In [ ]:
peng = np.genfromtxt("penguins_lter.csv", delimiter=",", dtype=str)
peng

array([['studyName', 'Sample_Number', 'Species', ...,
        'Flipper_Length_mm', 'Body_Mass_g', 'Sex'],
       ['PAL0708', '1', 'Adelie', ..., '181', '3750', 'MALE'],
       ['PAL0708', '2', 'Adelie', ..., '186', '3800', 'FEMALE'],
       ...,
       ['PAL0910', '122', 'Gentoo', ..., '222', '5750', 'MALE'],
       ['PAL0910', '123', 'Gentoo', ..., '212', '5200', 'FEMALE'],
       ['PAL0910', '124', 'Gentoo', ..., '213', '5400', 'MALE']],
      dtype='<U17')

In [ ]:
peng.shape

(345, 12)

In [ ]:
# Unique data
np.unique(peng[...,0])

array(['PAL0708', 'PAL0809', 'PAL0910', 'studyName'], dtype='<U17')

In [ ]:
np.unique([peng[...,-1]])

array(['', '.', 'FEMALE', 'MALE', 'Sex'], dtype='<U17')

In [ ]:
# Data Filteration
Male = peng[peng[...,-1]=='Male']
Male

array([], shape=(0, 12), dtype='<U17')

In [ ]:
l = input("Enter: ")
k = int(input("Enter: ")

result = []

for i in range(1, k + 1):
  result.append(l[-i])

result = result + l[:, len(l) - i]

Enter: 1 2 3 4 5
Enter: 2


TypeError: ignored